apikey: 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
test_defaults:
  to: rob@jugglerdigital.com
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: jim
  to_name: sdf
  reply_to: sadfasdf
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
